/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafos;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;

/**
 *
 * @author Samuel Santos
 */
public class InterfaceG extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceG
     */
    public InterfaceG() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGeraGrafo = new javax.swing.JButton();
        labelDestino = new javax.swing.JLabel();
        labelDepartamento = new javax.swing.JLabel();
        txtInputDestino = new javax.swing.JTextField();
        txtInputOrigem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGeraGrafo.setText("Encontrar o menor Caminho");
        buttonGeraGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGeraGrafoActionPerformed(evt);
            }
        });

        labelDestino.setText("Destino");

        labelDepartamento.setText("Origem:");

        txtInputDestino.setText("Informe o destino");
        txtInputDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtInputDestinoMouseClicked(evt);
            }
        });
        txtInputDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputDestinoActionPerformed(evt);
            }
        });

        txtInputOrigem.setText("Informe a origem");
        txtInputOrigem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtInputOrigemMouseClicked(evt);
            }
        });
        txtInputOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputOrigemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(buttonGeraGrafo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtInputOrigem)
                                .addComponent(txtInputDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txtInputOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInputDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(buttonGeraGrafo)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGeraGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGeraGrafoActionPerformed
        // TODO add your handling code here:
        String inicio = txtInputOrigem.getText();
        String fim = txtInputDestino.getText();
        
        try {
                String comando = "cmd.exe /c  python C:\\Users\\samue\\PycharmProjects\\graph\\graph.py "+ inicio + " " + fim;
                System.out.println(comando);
                Runtime.getRuntime().exec(comando);
        } catch (IOException ex) {
                   System.out.println(ex);
        }
        
    }//GEN-LAST:event_buttonGeraGrafoActionPerformed

    private void txtInputDestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInputDestinoMouseClicked
        // TODO add your handling code here:
        if(txtInputDestino.getText().equalsIgnoreCase("Informe o destino"))
            txtInputDestino.setText("");
    }//GEN-LAST:event_txtInputDestinoMouseClicked

    private void txtInputOrigemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInputOrigemMouseClicked
        // TODO add your handling code here:
        if(txtInputOrigem.getText().equalsIgnoreCase("Informe a origem"))
            txtInputOrigem.setText("");     
    }//GEN-LAST:event_txtInputOrigemMouseClicked

    private void txtInputOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputOrigemActionPerformed

    private void txtInputDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputDestinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               JFrame a  = new InterfaceG();
               a.setTitle("Menu");
               a.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGeraGrafo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDepartamento;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JTextField txtInputDestino;
    private javax.swing.JTextField txtInputOrigem;
    // End of variables declaration//GEN-END:variables
}
